### ISSUE TITLE
添加快捷键自定义

### ISSUE THREAD

**Issue by skefy** [Haojen/vimkey#1]
软件非常棒，UI也挺漂亮。

但是现在的快捷键和我自己的习惯不太符合，希望添加自定义快捷键的入口。

**Comment by Haojen** [comment]
> 软件非常棒，UI也挺漂亮。
> 
> 但是现在的快捷键和我自己的习惯不太符合，希望添加自定义快捷键的入口。

已添加该功能，新版本 Apple Store 正在审核，应该就这一两天就可以更新尝试了，再次感谢反馈
