### ISSUE TITLE
google search filter 不生效

### ISSUE THREAD

**Issue by y1rn** [Haojen/vimkey#10]
比如要過濾時間，到了日期選擇之後按F就不能彈出字母，其他按鍵也不生效

**Comment by Haojen** [comment]
@y1rn 感谢反馈，类似时间和日期等系统级别的组件，目前还无法选中，这是由于底层安全限制的原因。

**Comment by y1rn** [comment]
有時候打開頁面也是沒法使用，需要刷新頁面。也是這個原因嗎？

**Comment by Haojen** [comment]
@y1rn 你用的是 iPadOS or iOS 系统吗？ 如果是的话，是因为系统有安全限制，必须人为的点击一下页面才可以使用

**Comment by y1rn** [comment]
> @y1rn 你用的是 iPadOS or iOS 系统吗？ 如果是的话，是因为系统有安全限制，必须人为的点击一下页面才可以使用

ipados

**Comment by Haojen** [comment]
> > @y1rn 你用的是 iPadOS or iOS 系统吗？ 如果是的话，是因为系统有安全限制，必须人为的点击一下页面才可以使用
> 
> ipados

那这就是系统限制，没有办法。😂
