### ISSUE TITLE
设置里的滚动速度好像没有生效

### ISSUE THREAD

**Issue by quanuanc** [Haojen/vimkey#11]
改变滚动速度值后，网页的滚动速度和滚动距离都看不出有改变。

系统版本：macOS Monterey 12.6
Safari版本：版本16.0 (17614.1.25.9.10, 17614)

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/37785611/193447324-e2892320-7d1f-46ae-895b-3770126b8aae.png">

**Comment by Haojen** [comment]
@Quanuanc 辛苦反馈，请尝试卸载 Vimkey 后重新安装。因为最近的 2.6.0 版本有一些数据结构的改动，可能会影响到正常配置生效的问题。

**Comment by quanuanc** [comment]
尝试过卸载重新安装也不行。UD滚动速度那里，设置 100 和默认的 40 看不出区别。
可能跟 promotion 有关？我的机型是 MBP 14，在实验特性里开启了启用原生平滑滚动支持选项，关闭了启用原生平滑滚动支持按一下 d 键能滚动得远一点，但是改变滚动速度也一样看不出变化。

**Comment by Haojen** [comment]
@Quanuanc 确实，我设置100的时候也是这样，问题已经定位了，下个版本修复。感谢反馈

**Comment by quanuanc** [comment]
@Haojen 感谢

**Comment by Haojen** [comment]
@Quanuanc 今天着手修复，发现滚动速度问题是由于 Safari  浏览器自身滚动 Bug 所导致的，目前避开这个问题有两个方法。 方法一，在Vimkey设置-实验功能中关闭原生 macOS 的平滑滚动支持。方法二，调整更高的滚动速度，如 100， 200，500 ，800等，低于100效果不明显。

**Comment by quanuanc** [comment]
@Haojen 试着设置了一下 700，确实生效了，感谢。
