### ISSUE TITLE
按 f 无法显示任何字母

### ISSUE THREAD

**Issue by thescfai** [Haojen/vimkey#14]
不知道是啥情况，按 f 无法显示任何字母，其他功能诸如标签页切换，滚动之类正常

**Comment by Haojen** [comment]
Please provide more information, like operation steps,  website etc info.

**Comment by thescfai** [comment]
已经解决了，我用了 safari 偏好设置里头的自定义网页大小样式 css 文件，所以导致扩展产生 bug，取消样式列表 css 文件就恢复正常了，感谢作者的扩展，让我体验大增。
