### ISSUE TITLE
Some keys do not work properly in edit mode

### ISSUE THREAD

**Issue by blacksheepaul** [Haojen/vimkey#15]
在leetcode、Milkdown的代码编辑器中，可以删除部分文字，但不能删除一整行，也不能删除换行符。
如果需要，很乐意提供更多信息

System info:

- Safari Version 16.1 (17614.2.9.1.13, 17614)
- macOS Monterey 12.6.1
- MacBook Air M2

**Comment by Haojen** [comment]
Thank you feedback, I will check it soon. if you in any website get into some trouble you can use the [i] key to temporarily disable Vimkey or permanently disable Vimkey on the website.

**Comment by Haojen** [comment]
> 在leetcode、Milkdown的代码编辑器中，可以删除部分文字，但不能删除一整行，也不能删除换行符。 如果需要，很乐意提供更多信息
> 
> System info:
> 
> * Safari Version 16.1 (17614.2.9.1.13, 17614)
> * macOS Monterey 12.6.1
> * MacBook Air M2

Today I tried in Leetcode editor, and I think I've seen this problem too. The next version will fix it.  thank you feedback again.

**Comment by Haojen** [comment]
It's fixed, please try the 2.8 version
