### ISSUE TITLE
Safari环境下“f”键高亮不起作用

### ISSUE THREAD

**Issue by nscmiaoxin** [Haojen/vimkey#18]
Safari环境下“f”键高亮不起作用，其他的键都没有问题，Safari版本版本16.1 (18614.2.9.1.12)，系统版本13.0 (22A380)，不知道怎么回事儿

**Comment by Haojen** [comment]
@nscmiaoxin Make sure you have enabled Vimkey permissions

**Comment by nscmiaoxin** [comment]
> @nscmiaoxin确保您已启用 Vimkey 权限

是的，我确认开启了，JKHL键的功能都没有问题的，并且在Chrome插件上也都是没有问题的，唯一的问题就出现在Safari的F键上，高亮没有作用，我担心键位冲突，换了快捷键，依旧无法实现f键的作用，麻烦帮忙检查一下，谢谢！

**Comment by nscmiaoxin** [comment]
> @nscmiaoxin Make sure you have enabled Vimkey permissions

找到问题了，是和Dynamo插件有冲突，关掉dynamo就好了😓
