### ISSUE TITLE
Vimkey somehow conflicts with styles in nginx-proxy-manager

### ISSUE THREAD

**Issue by alexkuang0** [Haojen/vimkey#19]
## Descriptions

1. Vimkey somehow conflicts with styles in [nginx-proxy-manager][1].
2. I cannot turn the inject of Vimkey off unless I disable the extension completely.

## Screenshots

When Vimkey is enabled, the textbox can only display a very narrow view of the text I entered (I entered `aaaaaa`):

<img width="322" alt="image" src="https://user-images.githubusercontent.com/17879507/204588767-45842d7b-09f1-49fb-a04b-9a48d1f7d418.png">

When Vimkey is disabled, it works as expected:

<img width="332" alt="image" src="https://user-images.githubusercontent.com/17879507/204589359-56e77c29-6735-49b1-adf6-ff2f67378eff.png">

[1]: https://github.com/NginxProxyManager/nginx-proxy-manager

**Comment by Haojen** [comment]
@alexkuang0 Thank your feedback, this is a bug and the next version will fix it, and will be soon released.

**Comment by alexkuang0** [comment]
I would like to add one weird behavior: sometimes the extension blocks my `Backspace` when I'm editing text or code. And this problem seems to be popping up randomly without a pattern.
I **love** this extension but I have to disable it for now until these issues can be further identified and resolved, as they can be quite annoying when I'm trying to be productive.

**Comment by Haojen** [comment]
@alexkuang0   the new version now is waiting for App Store and Chrome Web Store review, and soon will be released.

**Comment by Haojen** [comment]
It's released, please try the new version
