### ISSUE TITLE
Need new shortcuts to restore closed tab

### ISSUE THREAD

**Issue by Harr0y** [Haojen/vimkey#2]
Hello, 
In Vimium now the shortcut key I use most frequently is X restore closed tab.x close current tab
This pair of shortcut keys is indeed very convenient, you can open and close web pages.
No extension supports this feature after switching to Safari.
Thanks

**Comment by Haojen** [comment]
@Harr0y  Hi,  X and x close now is available, but have a bug ,can't always work fine, I'm will be fix it in the next version. thank you feedback.
