### ISSUE TITLE
[Feature Request] Support remap Esc key or send `Ctrl + [` as Esc

### ISSUE THREAD

**Issue by hdykokd** [Haojen/vimkey#25]
Thanks for developing extension! 

When using the hardware keyboard on the iPad, it is inconvenient to type the Escape key, so it would be very nice if this is implemented.

**Comment by Haojen** [comment]
Thank you for support. for now you can on iPadOS setting custom the ```Escape``` Key to custom a key which you want. next version Vimkey may can custom ```Escape```. btw, if you have want to cancel  ```f``` features, just press any isn't target's key,  just like ```space``` or ```cmd``` key and then to cancel it.

**Comment by hdykokd** [comment]
> if you have want to cancel  f features, just press any isn't target's key, just like space or cmd key and then to cancel it.

This is good! Thank you.
