### ISSUE TITLE
希望加入在输入框失去焦点/获取焦点的功能

### ISSUE THREAD

**Issue by Quanuanc** [Haojen/vimkey#3]
Hi，这个插件整体上非常不错了。经过使用我发现还缺少退出/进入输入框的功能。
例如：在 google.com 的首页，用 vimium 可以按下 esc 键实现从输入框失焦点，按下 gi 再次把焦点集中在输入框。而 vimkey 好像还没有办法做到，必须用手指点击一下空白的地方才能失焦。

**Comment by Haojen** [comment]
@Quanuanc 
抱歉，回复的有点晚了，再次感谢反馈。这个问题主要是因为 Vimkey 是 Cross App （PC browser 和 iPadOS）两者的键位有所不同，对于这个插件来说，最大的区别就是 ESC 按键 iPad 本身是没有的。在第一版中只支持了基本功能，后续版本迭代一定会加入这方面的支持，再次感谢。

**Comment by quanuanc** [comment]
> @Quanuanc 抱歉，回复的有点晚了，再次感谢反馈。这个问题主要是因为 Vimkey 是 Cross App （PC browser 和 iPadOS）两者的键位有所不同，对于这个插件来说，最大的区别就是 ESC 按键 iPad 本身是没有的。在第一版中只支持了基本功能，后续版本迭代一定会加入这方面的支持，再次感谢。

感谢感谢

**Comment by Haojen** [comment]
@Quanuanc 新版本已经发布，欢迎试用和反馈。

**Comment by Haojen** [comment]
> > @Quanuanc 抱歉，回复的有点晚了，再次感谢反馈。这个问题主要是因为 Vimkey 是 Cross App （PC browser 和 iPadOS）两者的键位有所不同，对于这个插件来说，最大的区别就是 ESC 按键 iPad 本身是没有的。在第一版中只支持了基本功能，后续版本迭代一定会加入这方面的支持，再次感谢。
> 
> 感谢感谢

已增加输入框失去焦点/获取焦点的功能

本次更新：

新增[gi]键功能，可以对文本输入区域进行聚焦。

新增AB模式自定义键绑定，之前只支持AA模式。

新增实验功能选项，可以体验新功能。

提升ProMotion / 120Hz滚动体验，让滚动更流畅。

修复重置设置错误

修复按键绑定可能会冲突的问题

修复弹窗样式有时候会受到网页影响的问题
