### ISSUE TITLE
support search bookmarks and open by pressing shift-b

### ISSUE THREAD

**Issue by kennethnanwu** [Haojen/vimkey#31]
Thanks for this awesome plugin! one feature request: vimium supports this feature, I can search for my saved bookmarks and open the quickly by pressing 'B'. Could we also support this feature in Vimkey?

**Comment by Haojen** [comment]
Thank you for the feedback and share your love. I developed this feature and tested it on Chrome all was fine but when I tried it on Safari unfortunately Safari doesn't support Bookmark API, so I removed this feature temporarily, if Safari gets support I will add this feature as soon as I can.
