### ISSUE TITLE
Source code for the extension

### ISSUE THREAD

**Issue by nounder** [Haojen/vimkey#35]
Is this extension actually open source? This repo only contains sources to the website. I'd like to make some tweaks to my setup and verify the code before allowing it on every website.

**Comment by Haojen** [comment]
> Is this extension actually open source? This repo only contains sources to the website. I'd like to make some tweaks to my setup and verify the code before allowing it on every website.

here only provide the website of Vimkey, for business reasons, I can't open the source for now. I deeply understand your concern about privacy, I can promise that Vimkey doesn't collect any information,  if you are a web developer you can check the source from Devtool that Vimkey doesn't use any Network API, even any remote source of images.
