### ISSUE TITLE
能否加一个黑暗模式功能的开关

### ISSUE THREAD

**Issue by Quanuanc** [Haojen/vimkey#4]
此插件还自带了把网页背景变暗黑的功能吗？  
现阶段这个暗黑模式会导致挺多地方都看不清了。  
能否加一个开关禁用此功能
![img](https://user-images.githubusercontent.com/37785611/142727212-329251ce-01f2-408e-b933-7e2c14282c4a.gif)

**Comment by James-Harden-13-R** [comment]
他妈的，是有多脑瘫才能想出这个功能啊，乖乖做vim快捷键不好吗，这个暗黑模式就纯你妈脑瘫

**Comment by Haojen** [comment]
> 此插件还自带了把网页背景变暗黑的功能吗？ 现阶段这个暗黑模式会导致挺多地方都看不清了。 能否加一个开关禁用此功能 ![img](https://user-images.githubusercontent.com/37785611/142727212-329251ce-01f2-408e-b933-7e2c14282c4a.gif)

这个不是一个 feature，这是一个 bug, 下个版本会修复，感谢告知

**Comment by Haojen** [comment]
@Quanuanc 这不是一个 feature，这是一个 bug。刚开始开发初期版本肯定有很多需要完善的地方，非常欢迎友善的讨论和交流而不是谩骂和人身攻击，请阁下自爱。

**Comment by James-Harden-13-R** [comment]
> @Quanuanc 这不是一个 feature，这是一个 bug。刚开始开发初期版本肯定有很多需要完善的地方，非常欢迎友善的讨论和交流而不是谩骂和人身攻击，请阁下自爱。

我道歉！对不起，无论如何我也不应该这样发泄情绪的...抱歉对您造成困扰了orz

**Comment by Quanuanc** [comment]
> @Quanuanc 这不是一个 feature，这是一个 bug。刚开始开发初期版本肯定有很多需要完善的地方，非常欢迎友善的讨论和交流而不是谩骂和人身攻击，请阁下自爱。

@ 错人啦。上面那哥们确实不友善，我觉得没有必要，有问题提出来就好了。
还是很感谢有这个插件让iPad浏览网页体验提升了。

**Comment by James-Harden-13-R** [comment]
> > @Quanuanc 这不是一个 feature，这是一个 bug。刚开始开发初期版本肯定有很多需要完善的地方，非常欢迎友善的讨论和交流而不是谩骂和人身攻击，请阁下自爱。
> 
> @ 错人啦。上面那哥们确实不友善，我觉得没有必要，有问题提出来就好了。 还是很感谢有这个插件让iPad浏览网页体验提升了。

确实，是我的问题，昨天下午想在Safari上找Vimium的替代品，效果都不好，无能狂怒了，再次道歉！

**Comment by Haojen** [comment]
@James-Harden-13-R @Quanuanc  Sorry, so long. I release a new version, the new version is now waiting for Apple Store to review, I think they will be soon.

Here is the update:

- 新增自定义按键绑定和映射功能，根据自身习惯灵活自定义。

- 修复暗夜模式的样式会影响网页原本样式
- 修复在某些网页中无法滚动的问题
- 修复有时候无法探测到输入框的问题

- 重构设置页面的 UI，界面更直观友好
- 调整暗夜模式的界面，更美观。

**Comment by James-Harden-13-R** [comment]
> @James-Harden-13-R @Quanuanc Sorry, so long. I release a new version, the new version is now waiting for Apple Store to review, I think they will be soon.
> 
> Here is the update:
> 
> * 新增自定义按键绑定和映射功能，根据自身习惯灵活自定义。
> * 修复暗夜模式的样式会影响网页原本样式
> * 修复在某些网页中无法滚动的问题
> * 修复有时候无法探测到输入框的问题
> * 重构设置页面的 UI，界面更直观友好
> * 调整暗夜模式的界面，更美观。

我爱你！
