### ISSUE TITLE
Feature Request: Shortcut to switch to tab groups

### ISSUE THREAD

**Issue by wabu** [Haojen/vimkey#6]
It would be great to have keyboard shortcuts to switch tab groups:
- either for switching to the next / previous tab group
- or similar to "search tabs" to search for a tab group name

**Comment by Haojen** [comment]
Thank you again, the feature may take a while to think about the best solution, but I will add it, it's great.

**Comment by wabu** [comment]
Thank you and thanks for the great plugin in general :)
