### ISSUE TITLE
Feature Request: search tabs of all tab groups

### ISSUE THREAD

**Issue by wabu** [Haojen/vimkey#7]
It would be great to search not only for tab names inside the active tab group, but to search for tab names in all tab groups and automatically switch to that group when entering a tab on a different tab group.

**Comment by Haojen** [comment]
@wabu Great idea,  I will be adjusted in the next version. thank you feedback.

**Comment by Haojen** [comment]
@wabu  Sorry to say, unfortunately, Safari is not provided an API to do that. I also tried other methods, only can show other groups of tabs, but still can not switch them. so for now,  need Safari to support Tab Group API.

**Comment by wabu** [comment]
Thanks for looking it it
