### ISSUE TITLE
安装了插件以后各种网站的 cmd + K 快捷键无法使用

### ISSUE THREAD

**Issue by ghost** [Haojen/vimkey#8]
感谢开发这个插件，发现安装了插件以后各种网站的 cmd + K 快捷键无法使用，disable 也不行，比如这个 https://beta.reactjs.org ，不知道有没有办法解决？感谢

**Comment by Haojen** [comment]
@matt-shawn 抱歉带来的不便，请问是否已更新到最新版本（2.5.0），我在最新版本中测试 disable 和用 [i] 进行临时禁用都是可以 cmd + k 唤起测试页面的左侧搜索框。

如无更新，请更新至最新版本并刷新网页 。

**Comment by ghost** [comment]
更新以后可以了，感谢！
